name: p1label
description: A new Flutter project.
version: 1.0.0
        #เวลาอัพเดต apk จะเช็คที่ build number เป็นอย่างแรก
        #1.0.0 คือ เลข version number
        #+1 คือเลข build number

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # สำหรับ Icon บน iOS
  shared_preferences: ^2.0.15 # สำหรับเก็บข้อมูล local storage บน android/ios
  esc_pos_printer: ^4.1.0 # สำหรับ Wifi printer
  cross_scroll: ^0.0.75  # สำหรับ Show Scroll only
  # flutter_barcode_listener , visibility_detector สำหรับ detector barcode แล้ว เรียกใช้งานปุ่มใน screen
  # flutter_barcode_listener: ^0.1.3
  # visibility_detector: ^0.3.2
  device_info_plus: ^3.2.3 # สำหรับอ่านรายละเอียดอุปกรณ์
  network_info_plus: ^2.1.3 # สำหรับอ่านข้อมูลการเชื่อมต่อ Network เช่น IP, Macaddress
  audioplayers: ^0.20.1 # เล่นไฟล์เสียงรองรับ mp3, wav
  intl: ^0.17.0 # สำหรับจัดการทศนิยม วันที่ สกุลเงิน รองรับการทำงานของหลายประเทศ l10n
  flutter_localizations: # สำหรับเปลี่ยนภาษาข้อความ l10n เป็น dependencies ของ flutter sdk
    sdk: flutter
  provider: ^5.0.0 # สำหรับ state managament
  ota_update: ^4.0.1 # จัดการดาวน์โหลดและติดตั้งไฟล์ apk อัพเดต
  package_info_plus: ^1.4.2 # อ่านข้อมูลเวอร์ชั่น build number ของแอพ
  
  
  # สำหรับ generate icon ของแอพ
  # flutter_launcher_icons: ^0.9.2 
    # ถ้าใช้คำสั่ง flutter pub run flutter_launcher_icons:main แล้ว error ให้ใช้งานจาก git แทน
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8

flutter_icons: # ใช้กับ dependencies : flutter_launcher_icons
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/appicon/AppIconP1Label.png"
# แล้วใช้คำสั่ง flutter pub run flutter_launcher_icons:main


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0 # เช็ค standart dart coding

flutter:

  uses-material-design: true
  generate: true # generate tool ของ android อัติโนมัติทำงานตอน dev เมื่อเรียกใช้ l10n
  assets:
    - assets/images/appicon/
    - assets/images/bg/
    - assets/images/logo/
    - assets/data/
    - assets/audio/

  fonts:
    - family: IBMPlexSansThaiLooped
      fonts:
        - asset: fonts/IBMPlexSansThaiLooped-Thin.ttf # Thin 100
        - asset: fonts/IBMPlexSansThaiLooped-ExtraLight.ttf # ExtraLight 200
        - asset: fonts/IBMPlexSansThaiLooped-Light.ttf # Light 300
        - asset: fonts/IBMPlexSansThaiLooped-Regular.ttf # Regular 400
        - asset: fonts/IBMPlexSansThaiLooped-Medium.ttf # Medium 500